# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            'Angular Academy'
description:      'Your place to learn Angular Platform and best practices. Created by <a href="https://twitter.com/pietrucha/" target="_blank">@pietrucha</a>'
baseurl:          http://blog.angular-academy.com/

paginate:         5
